using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace olmelabs.battleship.api.Models.Entities
{
    public abstract class BsonBase
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
    }
}
