export const DUMMY = 'DUMMY';
export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const SIGNALR_ON_CONNECTED = 'SIGNALR_ON_CONNECTED';

export const SET_GAME_MODE = 'SET_GAME_MODE';
export const MAKE_FIRE = 'MAKE_FIRE';
export const MAKE_FIRE_SERVER = 'MAKE_FIRE_SERVER';
export const SHIP_DESTROYED = 'SHIP_DESTROYED';
export const SHOW_ENEMY_SHIPS = 'SHOW_ENEMY_SHIPS';

export const SHIP_MOVED = 'SHIP_MOVED';
export const SHIP_ROTATED = 'SHIP_ROTATED';
export const SHIP_INDEX_CHANGED = 'SHIP_INDEX_CHANGED';

export const BOARD_VALID = 'BOARD_VALID';
export const BOARD_INVALID = 'BOARD_INVALID';
export const BOARD_GENERATED = 'BOARD_GENERATED';

export const GameState = {
    NOT_STARTED: 'NOT_STARTED',
    STARTED: 'STARTED',
    COMPLETED: 'COMPLETED'
};

export const BoardType = {
    MY_BOARD: 'MY_BOARD',
    ENEMY_BOARD: 'ENEMY_BOARD',
};

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_LOGIN_FAILED = 'ACCOUNT_LOGIN_FAILED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REGISTER_RESET = 'ACCOUNT_REGISTER_RESET';
