version: '3.7'

services:
  olmelabs.battleship.api:
    image: ${DOCKER_REGISTRY}olmelabs/battleshipapi
    build:
      context: .
      dockerfile: olmelabs.battleship.api/Dockerfile
    ports:
      - "8091:80"
    #volumes:     
      # In case you need to share folder with host.  
      # Make sure drive sharing and credentials are properly configured on windows. Docker > Settings > Shared Drives.
      #- ${APPDATA}/Microsoft/UserSecrets/${USER_SECRETS_ID}:/root/.microsoft/usersecrets/${USER_SECRETS_ID}



